name: goreleaser

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install git-semver
        run: go install github.com/srbry/git-semver@10c3dca9978ca04c63f25f9f8c87d22d0deb2705
      - name: Bump tag if necessary
        id: tag
        run: |
          nextver=v$(git-semver)
          if [ -z $(git tag -l ${nextver}) ]; then
            git tag ${nextver}
            git push --tags
            echo "new=true" >> $GITHUB_OUTPUT
          fi
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: ${{ steps.tag.outputs.new == 'true' }}
        with:
          distribution: goreleaser
          version: 'v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
