name: static-linux

on:
  release:
    types:
      - published

jobs:
  static-linux:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Configure Git
        run: |
          git config --global user.name "Onionpipe CI"
          git config --global user.email "onionpipe-ci@users.noreply.github.com"

      - name: Build static binary
        working-directory: ${{ github.workspace }}
        run: |
          ./build/build_all_debian.bash

      - name: Upload linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_path: dist/onionpipe-linux-amd64-static
          asset_name: onionpipe-linux-amd64-static
          asset_content_type: application/octet-stream
          upload_url: ${{ github.event.release.upload_url }}
